{
  "model_config" : {
    "model_name": "pairwiserankerwithparameter",
    "pretrained": "yes",
  },
  "train_config": {
    "batch_size": 1024,
    "num_epochs": 100,
    "lr": 0.0003,
    "weight_decay": 0.003,
    "momentum": 0.9,
    "log_interval": 10,
    "num_workers": 0,
    "device": "cuda",
    "optimizer": "AdamW",
    "criterion": "BCEWithLogitsLoss",
    "scheduler": {
      "scheduler_name": "MultiStepLR",
      "milestones": [100, 150],
      "gamma": 0.1,
    },
    "patch_size": 128,
    "preprocess_type":"rgb",
    "seed": 100,
  },
  "post_temp_scaling" : "no",
  "data_config": {
    "train_data" : {
      "data_path": "input/dl_dataset/small_lots_train_pair_ranker_data.csv",
      "augmentations": {
        "ToPILImage": {},
        "AugMix": {"severity": 10 , "mixture_width": 20},
        "GaussianBlur": {
          "kernel_size": 3,
          "sigma": [0.01,1]
        },
        "Resize": {"size": [50, 50],
        "interpolation": 2
        },
        "ToTensor": {}
      }
    },
    "test_data" : {
      "data_path": "input/dl_dataset/diy_test_pair_ranker_data.csv",
      "augmentations": {
        "ToPILImage": {},
        "Resize": {"size": [50, 50]},
        "ToTensor": {}
      },
    },
  },
}
